<?php require_once "./dodawanie_do_tabeli.php" ?>

<html>
	<head>
		<meta charset="utf8">
		<title>Dziupla Marecka</title>
		<link href="style.css" rel="stylesheet">
		<link rel="icon" href="golomp.jpg" type="image/gif" sizes="16x16">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,600,1,0" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body>
		<center>
		<section id="sekcja_tytulowa">
			Dziupla Marecka
		</section>
		<section id="sekcja_linkowa">
				<a href="./../../index.php"><span class="material-symbols-outlined">home</span></a><!-- naprawic tego linka o sie zesrał -->
		</section>
			<br>
			<br>
			<div id="tytul_tabeli">
				<span class="material-symbols-outlined">arrow_downward</span> Pliki przechowywane w kanale <span class="material-symbols-outlined">arrow_downward</span>
			</div>
			<div id="tablica_z_plikami">
				<?php require_once "./wyswietlanie_tabeli.php"?>
			</div>
			<br>
			<br>
			<div id="wyslij">
				<a href="wyslij.php">Wyślij nowy plik</a>
			</div>
			<br>
			<br>

			</center>
			<footer>
			<hr>
			<br>
			<center>Autrostwo: Mareckie koło miłośników  ludzików z kasztanów <br> --- <br>Generated by: Mlekovita Sp. Z.O.O</center>
		</footer>
	</body>
</html>
