<html>
  <head>
    <meta charset="utf8">
    <title>Dziupla Marecka</title>
    <link href="style.css" rel="stylesheet">
    <link rel="icon" href="golomp.jpg" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,600,1,0" />
  </head>
  <body>
    <center>
      <section id="sekcja_tytulowa">
        Witamy w Dziupli Mareckiej
      </section>
    <section id="sekcja_linkowa">
      <a href="patchnotes.html"><span class="material-symbols-outlined">note</span></a>
      <a href="strona_w_budowie-template.html"><span class="material-symbols-outlined">info</span></a>
      <a href="strona_w_budowie-template.html"><span class="material-symbols-outlined">movie</span></a>
      <a href="strona_w_budowie-template.html"><span class="material-symbols-outlined">qr_code_2</span></a>
    </section>
    <?php/* require_once "licznik_plikow.php" */?> <!-- do naprawy, zesralo sie przy custom'owych nazwach kanałów -->
    <section id ="sekcja_kanalow">
    <?php require_once "./wyswietlanie_kanalow.php" ?>
    </section>
    <br>
    <section id="sekcja_dodawania_kanalu">
      <br>
      <a href="./edycja_kanalow/edycja_kanalu.php">Edytuj kanały</a>
    </section>
    <br>
    <?php require_once "./zlicz.php" ?>
    <br>
    <br>
    <br>
    Do końca roku zostało:<div id="time"><script src="data_counter.js"></script></div>
    <br>
    <div id="cookies-message-container">  <!-- naprawic sciezke z ciaskammi bo tez sie popsulo-->
      <div id="cookies-message">
          Ta strona używa ciasteczek.... I chuj CI do tego jak nieakceptujesz to <b>wypierdalaj</b> : - D
          <a onclick="WHCloseCookiesWindow();" id="accept-cookies-checkbox">OK OK</a>
      </div>
    </div>
    <script src="ciastka-okienko.js"></script>
    </center>
    <footer>
    <hr>
    <br>
      <center>Autrostwo: Mareckie koło miłośników  ludzików z kasztanów <br> --- <br>Generated by: Mlekovita Sp. Z.O.O</center>
    </footer>
  </body>
</html>