<html>
	<head>
		<meta charset="utf8">
		<title>Dziupla Marecka</title>
		<link href="style.css" rel="stylesheet">
		<link rel="icon" href="golomp.jpg" type="image/gif" sizes="16x16">
		<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,600,1,0" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body>
		<section id="sekcja_tytulowa">
			Dodaj nowy kanał
		</section>
			<main>
				<form method="post">
					<label>Wprowadź nazwę kanału:</label>
					<input type ="text" id="nazwa_kanalu" name="nazwa_kanalu" maxlength="15" required="required">
					<b>Maksymalna ilość znaków: 15</b>
					<br>
					<button type="submit"><b>Utwórz</b></button>
					<br>
				<a href="edycja_kanalu.php">Powrót</a>
				</form>
				
				<?php require_once "./kopiowanie_szblony_foldera.php" ?>
			</main>
			<footer id="stopka_dla_dodawania">
			<hr>
			<br>
			<center>Autrostwo: Mareckie koło miłośników  ludzików z kasztanów <br> --- <br>Generated by: Mlekovita Sp. Z.O.O</center>
		</footer>
	</body>
</html>
