<html>
    <head>
        <meta charset="utf8">
        <title>Dziupla Marecka</title>
        <link href="style.css" rel="stylesheet">
        <link rel="icon" href="golomp.jpg" type="image/gif" sizes="16x16">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,600,1,0" />
  </head>
  <body>
    <section id="sekcja_tytulowa">
	    Edycja kanałów
    </section>
    <section id="sekcja_linkowa">
        <a href="./../index.php"><span class="material-symbols-outlined">home</span></a>
    </section>

 
    <section id="sekcja_kanalow">
    <?php require_once "tabela.php" ?>
        
    </section>
    <br>
    <section id="sekcja_dodawania_kanalu">
        <center><a href="dodaj_kanal.php">Dodaj nowy kanał</a></center>
    </section>
     <br>
    <footer>
	        <hr>
	        <br>
	        <center>Autrostwo: Mareckie koło miłośników  ludzików z kasztanów <br> --- <br>Generated by: Mlekovita Sp. Z.O.O</center>
    </footer>


 
<?php
   // rmdir('./KANAŁY/kanalll'); 
   // header("Location: ./index.php");
?>
    </body>
</html>